export const ANNOTATION_ACTIONS = {
  UPDATE_TOOL_INSTANCE: '@@UPDATE_TOOL_INSTANCE',
  UPDATE_IMG_LIST: '@@UPDATE_IMG_LIST',
  UPDATE_ATTRIBUTE_LIST: '@@UPDATA_ATTRIBUTE_LIST',
  UPDATE_TOOLS_CONFIG:'@@UPDATE_TOOLS_CONFIG',
  UPDATE_TAG_LIST: '@@UPDATE_TAG_LIST',
  UPDATE_CURRENT_TOOLNAME:'@@UPDATE_CURRENT_TOOLNAME',
  UPDATE_ANNOTATION_CONFIG: '@@UPDATE_ANNOTATION_CONFIG',
  LOAD_FILE_DATA: '@@LOAD_FILE_DATA',
  SUBMIT_FILE_DATA: '@@SUBMIT_FILE_DATA',
  SET_TASK_CONFIG: '@@SET_TASK_CONFIG',
  INIT_TOOL: '@@INIT_TOOL',
  SET_TOOL: '@@SET_TOOL',
  UPDATE_ON_SUBMIT: '@@UPDATE_ON_SUBMIT',
  UPDATE_ON_SAVE: '@@UPDATE_ON_SAVE',
  UPDATE_ON_PAGE_CHANGE: '@@UPDATE_ON_PAGE_CHANGE',
  UPDATE_ON_STEP_CHANGE: '@@UPDATE_ON_STEP_CHANGE',
  UPDATE_TEXT_CONFIG:'@@UPDATE_TEXT_CONFIG',
  UPDATE_ROTATE: '@@UPDATE_ROTATE',
  UPDATE_GET_FILE_DATA: '@@UPDATE_GET_FILE_DATA',
  UPDATE_PAGE_SIZE: '@@UPDATE_PAGE_SIZE',
  UPDATE_LOAD_FILE_LIST: '@@UPDATE_LOAD_FILE_LIST',
  GET_FILE_DATA: '@@GET_FILE_DATA',
  SET_FILE_DATA: '@@SET_FILE_DATA',
  COPY_BACKWARD_RESULT: '@@COPY_BACKWARD_RESULT',
  SET_STEP: '@@SET_STEP',
  SUBMIT_RESULT: '@@SUBMIT_RESULT',
  SAVE_RESULT: '@@SAVE_RESULT',
  SAVE_LABELRESULT: '@@SAVE_LABELRESULT',
  SAVE_LABEL_FILE_DATA:'@@SUBMIT_LABEL_FILE_DATA',
  SET_BASIC_INDEX: '@@SET_BASIC_INDEX',
  CALC_STEP_PROGRESS: '@@CALC_STEP_PROGRESS',
  SET_TRIGGER_EVENT_AFTER_INDEX_CHANGED: '@@SET_TRIGGER_EVENT_AFTER_INDEX_CHANGED',
  UPDATE_IS_SHOW_ORDER:'@@UPDATE_IS_SHOW_ORDER',
  UPDATE_IS_SHOW_ATTRIBUTE_TEXT:'@@UPDATE_IS_SHOW_ATTRIBUTE_TEXT',
  UPDATE_IS_SHOW_ATTRIBUTE:'@@UPDATE_IS_SHOW_ATTRIBUTE',
  UPDATE_IS_SHOW_DIRECTION:'@@UPDATE_IS_SHOW_DIRECTION',

  SET_LOADING: '@@SET_LOADING',
};

export const IMAGE_ATTRIBUTE_ACTIONS = {
  UPDATE_IMG_ATTRIBUTE: '@@UPDATE_IMG_ATTRIBUTE',
  INIT_IMG_ATTRIBUTE: '@@INIT_IMG_ATTRIBUTE',
};

export const TOOL_STYLE_ACTIONS = {
  INIT_TOOL_STYLE_CONFIG: '@@INIT_TOOL_STYLE_CONFIG',
  UPDATE_TOOL_STYLE_CONFIG: '@@UPDATE_TOOL_STYLE_CONFIG',
  UPDATE_COLLAPSE_STATUS:'@@UPDATE_COLLAPSE_STATUS'
};
