export enum ToolName {
  /** 拉框工具 */
  Rect = 'rect',
  /** 标点工具 */
  Point = 'point',
  /** 多边形工具 */
  Polygon = 'polygon',
  /** 线条 */
  Line = 'line',
  /** 标签工具 */
  Tag = 'tag',
  /** 文本工具 */
  Text = 'text',
  /** 列表标点工具 */
  PointMarker = 'point-marker',
  /** 前景分割工具 */
  Segmentation = 'segmentation',
  /** 筛选工具 */
  Filter = 'filter',
  /** 列表线条工具 */
  LineMarker = 'line-marker',
  /** 文件夹标签工具 */
  FolderTag = 'folder-tag',
  /** 拉框跟踪工具 */
  RectTrack = 'rect-track',
  /** 人脸106工具 */
  Face = 'face',
  /** 客户端属性工具 */
  ClientAttribute = 'client-attribute',
  /** OCR关联关系工具 */
  OCRRelation = 'OCR-relation',
}
